treasurer.register_treasure("gps:gps",0.0001,6,{1,2},nil,"tool")

treasurer.register_treasure("fun_tools:chainsaw",0.0001,6,{1,2},nil,"tool")
treasurer.register_treasure("fun_tools:jackhammer",0.0001,6,{1,2},nil,"tool")
treasurer.register_treasure("fun_tools:flare_gun",0.001,6,{1,2},nil,"tool")
treasurer.register_treasure("fun_tools:rope_ladder_10",0.01,4,{1,5},nil,"ladder")

treasurer.register_treasure("integral:moon_juice",0.0002,6,1,nil,"crafting_component")
treasurer.register_treasure("default:shovel_bronze",0.006,6,nil,nil,"minetool")
treasurer.register_treasure("integral:glowing_fungus",0.001,5,{1,5},nil,"crafting_component")

treasurer.register_treasure("unified_inventory:bag_small",0.00005,5,1,nil,"tool")
treasurer.register_treasure("unified_inventory:bag_medium",0.00002,6,1,nil,"tool")
treasurer.register_treasure("unified_inventory:bag_large",0.00001,7,1,nil,"tool")

treasurer.register_treasure("farming:hemp_leaf",0.01,3,{1,5},nil,"crafting_component")
treasurer.register_treasure("farming:hemp_seed",0.01,3,{1,5},nil,"crafting_component")
treasurer.register_treasure("farming:potato",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:tomato",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:corn",0.01,4,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:coffee_beans",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:raspberries",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:rhubarb",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:blueberries",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:beans",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:grapes",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:carrot",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:cucumber",0.01,3,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:melon",0.01,4,{1,5},nil,"raw_food")
treasurer.register_treasure("farming:pumpkin",0.01,4,{1,5},nil,"raw_food")

treasurer.register_treasure("moreores:mithril_ingot",0.002,9,{2,4},nil,"building_block")
treasurer.register_treasure("moreores:mithril_block",0.001,10,1,nil,"building_block")
treasurer.register_treasure("underworlds:hot_stone",0.005,5,{2,4},nil,"building_block")

treasurer.register_treasure("handholds:climbing_pick",0.005,9,1,nil,"minetool")
treasurer.register_treasure("moreores:pick_silver",0.002,10,1,nil,"minetool")
treasurer.register_treasure("moreores:shovel_silver",0.002,10,1,nil,"minetool")
treasurer.register_treasure("moreores:sword_silver",0.002,10,1,nil,"minetool")
treasurer.register_treasure("moreores:pick_mithril",0.002,10,1,nil,"minetool")
treasurer.register_treasure("moreores:shovel_mithril",0.002,10,1,nil,"minetool")
treasurer.register_treasure("moreores:axe_mithril",0.005,10,1,nil,"minetool")
treasurer.register_treasure("moreores:sword_mithril",0.005,10,1,nil,"melee_weapon")
treasurer.register_treasure("mobs:pick_lava",0.001,10,1,nil,"minetool")
treasurer.register_treasure("mobs:lava_orb",0.005,9,1,nil,"minetool")
